@startuml

<style>
rectangle {
  Fontcolor green
  HorizontalAlignment center
}
</style>

left to right direction
actor Utilisateur as E
actor Administrateur as A

rectangle "Gestion des Formations" {

  A --> (Gérer les formations)
  A --> (Gérer les modules)
  A --> (Gérer les quiz)
  A --> (Générer rapports)

  E --> (Consulter catalogue formations)
    E --> (S'inscrire à une formation)
    E --> (Consulter contenu module)
    E --> (Passer un quiz)
    E --> (Passer le test final)
    E --> (Télécharger certification)

  (Passer un quiz) .> (Consulter contenu module) : include
  (Passer le test final) .> (S'inscrire à une formation) : extend
  (Télécharger certification) <.. (Passer le test final) : si réussi
  (S'inscrire à une formation) .> (Consulter catalogue formations) : extend
}

@enduml